apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kokorotts-api
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "1"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/memory: "4Gi"
        run.googleapis.com/cpu: "2"
    spec:
      containerConcurrency: 10
      timeoutSeconds: 300
      containers:
      - image: gcr.io/YOUR_PROJECT/kokorotts-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: RATE_LIMITING_ENABLED
          value: "true"
        - name: DEPLOYMENT_MODE
          value: "cloud"
        - name: DEBUG
          value: "false"
        - name: LOG_LEVEL
          value: "INFO"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8000"
        - name: CORS_ORIGINS
          value: "https://yourdomain.com"
        - name: TRUST_PROXY_HEADERS
          value: "true"
        - name: RATE_LIMIT_REQUESTS_PER_MINUTE
          value: "30"
        - name: RATE_LIMIT_REQUESTS_PER_HOUR
          value: "200"
        - name: RATE_LIMIT_REQUESTS_PER_DAY
          value: "1000"
        - name: RATE_LIMIT_MAX_CHARS_PER_REQUEST
          value: "5000"
        - name: RATE_LIMIT_CHARS_PER_HOUR
          value: "50000"
        - name: RATE_LIMIT_CHARS_PER_DAY
          value: "200000"
        - name: RATE_LIMIT_MAX_CONCURRENT
          value: "3"
        - name: RATE_LIMIT_USE_REDIS
          value: "true"
        - name: REDIS_URL
          value: "redis://your-memorystore-instance:6379/0"
        - name: MAX_TEXT_LENGTH
          value: "50000"
        - name: DEFAULT_LANGUAGE
          value: "a"
        - name: VOICE_CACHE_DURATION
          value: "3600"
        - name: MAX_WORKERS
          value: "4"
        - name: REQUEST_TIMEOUT
          value: "300"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3